# encoding: utf-8

def notify m
  msg = "'#{m} at #{Time.now.to_s}'"
  if system "terminal-notifier -message #{msg}"
    return
  end

  if system "notify-send #{msg}"
    return
  end

  if system "tmux display-message #{msg}"
    return
  end

  STDERR.puts 'Sending notification failed'
end

guard :shell do
  watch /^(?:\.\.\/(?:autoload|plugin)|t)\/.+\.vim$/ do |m|
    puts "FOO!: #{m[0]}"
    unless system 'rake test'
      notify 'vim-flavor: Some test failed'
    end
  end
end
